### ISSUE TITLE
gonum.org does not serve go modules

### ISSUE THREAD

**Issue by sranka** [gonum/website#9]
I am not sure if this is the right place to post an issue, I tried to post a message  to https://groups.google.com/forum/#!forum/gonum-dev , it failed since I am not authorized to post.

```
go get -u -t gonum.org/v1/gonum/...
```

fails, because gonum.org web site does not serve go modules anymore. All projects that depend on gonum.org fail to compile in CI environments with a root cause:

```
Parsing meta tags from https://gonum.org/v1/netlib?go-get=1 (status code 404)
```

It worked fine 2 days ago. Can you please fix the gonum.org web site?

There is a workaround in 
https://github.com/influxdata/chronograf/pull/5520 , but it is IMHO not a good solution.

**Comment by kortschak** [comment]
We swapped over builds of the website yesterday, so that it likely the cause. However, the new site is displaying the needed meta tags for go get to work and the command you have posted works for me here.

Given this, it's hard for me to know how to proceed. Could you please paste the output of `go env` and `go version` here?

**Comment by kortschak** [comment]
Looking through the Go source for the error that you have posted, it looks like you are running Go 1.12.x (the error "Parsing meta tags from https..." was last in the Go tree in May last year). This is not a supported version of Go.

**Comment by kortschak** [comment]
The issue is that 404 pages are not examined further. It appear that this also affects gddo. I had a thought that maybe the direct get would replicate, and it does.

```
$ GOPROXY=direct go get gonum.org/v1/gonum
go get gonum.org/v1/gonum: unrecognized import path "gonum.org/v1/gonum": reading https://gonum.org/v1/gonum?go-get=1: 404 Not Found
```

However, if I look at the results from curl, I can see the meta-data with the correct values.

**Comment by kortschak** [comment]
I think I have found the cause of this.

Hugo's minification strips the quotes from the name attribute of the metatags.

~~Unfortunately I don't have access to the build config for the site, so will have to wait for @btracey. The fix should be to remove the `--minify` flag from the "Build command" in settings/deploys so that it is `hugo --gc -b $URL`, at least until a proper fix is made in hugo.~~ This can be done in the netlify.toml :smile: 

I have filed an issue for this there: gohugoio/hugo#7415

**Comment by kortschak** [comment]
This is working now. I will not mark it as fixed as I want the minification back, but not while it's broken.

**Comment by kortschak** [comment]
That was an unpleasant 4 hours.

**Comment by sranka** [comment]
Thank you for your quick action herein, I confirm that it is working.

**Comment by rcurtin** [comment]
Thanks @kortschak! :+1:
